# Generated by Django 3.2.9 on 2021-11-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(null=0)),
                ('dislike', models.IntegerField(null=0)),
                ('commentText', models.CharField(max_length=150)),
                ('videoId', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
